### ISSUE TITLE
crash in android 7.1.1

### ISSUE THREAD

**Issue by mandelmonkey** [TGIO/RNCryptorNative#16]
Seems to be crashing in the latest android, 

**# device details are**

Name: Nexus_5X_API_25_64bit

CPU/ABI: Google APIs Intel Atom (x86)

Path: C:\Users\chris\.android\avd\Nexus_5X_API_25_64bit.avd

Target: google_apis [Google APIs] (API level 25)

Skin: nexus_5x

SD Card: 100M

hw.dPad: no

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: Nexus 5X

vm.heapSize: 64

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.initialOrientation: Portrait

image.androidVersion.api: 25

hw.audioInput: yes

image.sysdir.1: system-images\android-25\google_apis\x86\

tag.id: google_apis

showDeviceFrame: yes

hw.camera.back: emulated

hw.mainKeys: no

AvdId: Nexus_5X_API_25_64bit

hw.camera.front: emulated

hw.lcd.density: 420

avd.ini.displayname: Nexus 5X API 25 64bit

hw.gpu.mode: auto

hw.device.hash2: MD5:1be89bc42ec9644d4b77968b23474980

hw.ramSize: 1536

hw.trackBall: no

hw.battery: yes

hw.cpu.ncore: 4

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

hw.keyboard: yes

hw.sensors.proximity: yes

disk.dataPartition.size: 800M

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes

**# crash details**

11-25 02:48:47.096 4588-4588/com.mandelduck.takara E/UncaughtException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz" referenced by "/data/app/com.mandelduck.takara-1/lib/x86/librncrypto.so"...
                                                                            at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                                            at java.lang.System.loadLibrary(System.java:1530)
                                                                            at tgio.rncryptor.RNCryptorNative.<clinit>(RNCryptorNative.java:33)
                                                                            at com.mandelduck.takara.MapsActivity.<init>(MapsActivity.java:167)
                                                                            at java.lang.Class.newInstance(Native Method)
                                                                            at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
11-25 02:48:47.110 4588-5415/com.mandelduck.takara I/DynamiteModule: Considering local module com.google.android.gms.tagmanager:7 and remote module com.google.android.gms.tagmanager:7
11-25 02:48:47.110 4588-5415/com.mandelduck.takara I/DynamiteModule: Selected local version of com.google.android.gms.tagmanager
11-25 02:48:47.133 4588-5415/com.mandelduck.takara W/GoogleTagManager: No container asset found in /assets/containers. Checking top level /assets directory for container assets.
11-25 02:48:47.133 4588-5415/com.mandelduck.takara W/GoogleTagManager: Tag Manager's event handler WILL NOT be installed (no container loaded)
11-25 02:48:47.133 4588-5415/com.mandelduck.takara I/GoogleTagManager: Tag Manager initilization took 2ms

**Comment by johnernest02** [comment]
Any updates on this issue?

**Comment by aslak-dirdal** [comment]
Any news on this?

**Comment by kurtheiligmann** [comment]
Having the same issue. Is this the same as #8? Similar error.

**Comment by enricodeleo** [comment]
+1

**Comment by oskitar89** [comment]
I am also getting this error with Android 7.0 emulator (genymotion), but it works with a real mobile with Android 5.1 x86 and Android 7.1.1 x86 emulator.  Is there a way to fix this? With Android Gradle Experimental don't work.

**Comment by mandelmonkey** [comment]
I catch the crash and then load JNCryptor library instead now

**Comment by getsadzeg** [comment]
What do you mean?

**Comment by mandelmonkey** [comment]
This library JNCryptor is the same but with slower performance, however its
doesnt crash on x86 devices
https://github.com/RNCryptor/JNCryptor

so I try and use RNCryptor native as its faster but if it crashes on a
device I catch the exception and load JNCryptor instead

**Comment by getsadzeg** [comment]
I got it.

**Comment by TGIO** [comment]
fixed with https://github.com/TGIO/RNCryptorNative/commit/5209f10b988e4033c0b769a40b0d6cc99ea16af7
